version: '3.8'

services:
  frontend_service:
    build:
      context: ../frontend2/frontend
    ports:
      - "4200:4200"  # Mapping des Ports für den Angular-Entwicklungsserver
    volumes:
      - ./src:/app/src  # Mounten des Quellcodes, damit Änderungen direkt reflektiert werden

networks:
  default:
    external: true
