services:
  app:
    image: mbirk2/calory-count
    container_name: calory-count
    ports:
      - "8080:80"
    deploy:
      update_config:
        parallelism: 1
        order: start-first
    restart: always
    pull_policy: always
