services:
  app:
    image: mbirk2/calory-count
    container_name: calory-count
    ports:
      - "8080:80"
    deploy:
      update_config:
        parallelism: 1
        order: start-first
    restart: always
    pull_policy: always
  calory-db:
    image: 'postgres:16.3'
    container_name: calory-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=calory-db
      - POSTGRES_PASSWORD=V40jN2gavmfj1q9Ln5Aq
      - PGUSER=calory-db
      - POSTGRES_DB=calory-db
