# Profile
spring.profile.active=dev

# Hibernate
spring.hibernate.ddl-auto=update

# Datasource
spring.datasource.password=V40jN2gavmfj1q9Ln5Aq
spring.datasource.username=calory-db
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/calory-db
spring.datasource.driverClassName=org.postgresql.Driver

# Flyway
spring.flyway.enabled=true
spring.flyway.check-location=false
spring.flyway.locations=classpath:/db/dev, /db/migration/

# Logging
logging.level.com.zaxxer.hikari=DEBUG

# Security
# JWT_SECRET must be provided as an environment variable (>= 256 bit / 32 chars).
jwt.secret=2cMcbtVuWT8mPEUjXHiBhb0tSeDuGTmXFoduH5BcTA4=