on:
  push:
    branches:
      - master  # Ändere dies entsprechend deines Branch-Namens

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      run: | 
        sudo apt-get install -y openjdk-21-jdk
          echo "::add-path::/usr/lib/jvm/java-21-openjdk-amd64/bin"

    - name: Verify Java version
      run: java -version

    - name: Build with Maven
      run: mvn -B package --file pom.xml