on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDk 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'
      - name: Test application
        working-directory: ./backend
        run: mvn test

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Build with Maven
        working-directory: ./backend
        run: mvn -B install -DskipTests